export interface Country {
  label: string;
  value: string | undefined;
  icon: string;
}

export const COUNTRIES: Country[] = [
  { label: 'Global', value: undefined, icon: '🌍' },
  { label: 'Nigeria', value: 'NG', icon: '🇳🇬' },
  // A
  { label: 'Afghanistan', value: 'AF', icon: '🇦🇫' },
  { label: 'Albania', value: 'AL', icon: '🇦🇱' },
  { label: 'Algeria', value: 'DZ', icon: '🇩🇿' },
  { label: 'Andorra', value: 'AD', icon: '🇦🇩' },
  { label: 'Angola', value: 'AO', icon: '🇦🇴' },
  { label: 'Argentina', value: 'AR', icon: '🇦🇷' },
  { label: 'Armenia', value: 'AM', icon: '🇦🇲' },
  { label: 'Australia', value: 'AU', icon: '🇦🇺' },
  { label: 'Austria', value: 'AT', icon: '🇦🇹' },
  { label: 'Azerbaijan', value: 'AZ', icon: '🇦🇿' },
  // B
  { label: 'Bahrain', value: 'BH', icon: '🇧🇭' },
  { label: 'Bangladesh', value: 'BD', icon: '🇧🇩' },
  { label: 'Barbados', value: 'BB', icon: '🇧🇧' },
  { label: 'Belarus', value: 'BY', icon: '🇧🇾' },
  { label: 'Belgium', value: 'BE', icon: '🇧🇪' },
  { label: 'Belize', value: 'BZ', icon: '🇧🇿' },
  { label: 'Benin', value: 'BJ', icon: '🇧🇯' },
  { label: 'Bhutan', value: 'BT', icon: '🇧🇹' },
  { label: 'Bolivia', value: 'BO', icon: '🇧🇴' },
  { label: 'Bosnia and Herzegovina', value: 'BA', icon: '🇧🇦' },
  { label: 'Botswana', value: 'BW', icon: '🇧🇼' },
  { label: 'Brazil', value: 'BR', icon: '🇧🇷' },
  { label: 'Bulgaria', value: 'BG', icon: '🇧🇬' },
  { label: 'Burkina Faso', value: 'BF', icon: '🇧🇫' },
  { label: 'Burundi', value: 'BI', icon: '🇧🇮' },
  // C
  { label: 'Cambodia', value: 'KH', icon: '🇰🇭' },
  { label: 'Cameroon', value: 'CM', icon: '🇨🇲' },
  { label: 'Canada', value: 'CA', icon: '🇨🇦' },
  { label: 'Cape Verde', value: 'CV', icon: '🇨🇻' },
  { label: 'Central African Republic', value: 'CF', icon: '🇨🇫' },
  { label: 'Chad', value: 'TD', icon: '🇹🇩' },
  { label: 'Chile', value: 'CL', icon: '🇨🇱' },
  { label: 'China', value: 'CN', icon: '🇨🇳' },
  { label: 'Colombia', value: 'CO', icon: '🇨🇴' },
  { label: 'Comoros', value: 'KM', icon: '🇰🇲' },
  { label: 'Congo', value: 'CG', icon: '🇨🇬' },
  { label: 'Costa Rica', value: 'CR', icon: '🇨🇷' },
  { label: 'Croatia', value: 'HR', icon: '🇭🇷' },
  { label: 'Cuba', value: 'CU', icon: '🇨🇺' },
  { label: 'Cyprus', value: 'CY', icon: '🇨🇾' },
  { label: 'Czech Republic', value: 'CZ', icon: '🇨🇿' },
  // D
  { label: 'Denmark', value: 'DK', icon: '🇩🇰' },
  { label: 'Djibouti', value: 'DJ', icon: '🇩🇯' },
  { label: 'Dominican Republic', value: 'DO', icon: '🇩🇴' },
  // E
  { label: 'Ecuador', value: 'EC', icon: '🇪🇨' },
  { label: 'Egypt', value: 'EG', icon: '🇪🇬' },
  { label: 'El Salvador', value: 'SV', icon: '🇸🇻' },
  { label: 'Estonia', value: 'EE', icon: '🇪🇪' },
  { label: 'Ethiopia', value: 'ET', icon: '🇪🇹' },
  // F
  { label: 'Fiji', value: 'FJ', icon: '🇫🇯' },
  { label: 'Finland', value: 'FI', icon: '🇫🇮' },
  { label: 'France', value: 'FR', icon: '🇫🇷' },
  // G
  { label: 'Gabon', value: 'GA', icon: '🇬🇦' },
  { label: 'Gambia', value: 'GM', icon: '🇬🇲' },
  { label: 'Georgia', value: 'GE', icon: '🇬🇪' },
  { label: 'Germany', value: 'DE', icon: '🇩🇪' },
  { label: 'Ghana', value: 'GH', icon: '🇬🇭' },
  { label: 'Greece', value: 'GR', icon: '🇬🇷' },
  { label: 'Greenland', value: 'GL', icon: '🇬🇱' },
  { label: 'Grenada', value: 'GD', icon: '🇬🇩' },
  { label: 'Guatemala', value: 'GT', icon: '🇬🇹' },
  { label: 'Guinea', value: 'GN', icon: '🇬🇳' },
  // H
  { label: 'Haiti', value: 'HT', icon: '🇭🇹' },
  { label: 'Honduras', value: 'HN', icon: '🇭🇳' },
  { label: 'Hong Kong', value: 'HK', icon: '🇭🇰' },
  { label: 'Hungary', value: 'HU', icon: '🇭🇺' },
  // I
  { label: 'Iceland', value: 'IS', icon: '🇮🇸' },
  { label: 'India', value: 'IN', icon: '🇮🇳' },
  { label: 'Indonesia', value: 'ID', icon: '🇮🇩' },
  { label: 'Iran', value: 'IR', icon: '🇮🇷' },
  { label: 'Iraq', value: 'IQ', icon: '🇮🇶' },
  { label: 'Ireland', value: 'IE', icon: '🇮🇪' },
  { label: 'Israel', value: 'IL', icon: '🇮🇱' },
  { label: 'Italy', value: 'IT', icon: '🇮🇹' },
  { label: 'Ivory Coast', value: 'CI', icon: '🇨🇮' },
  // J
  { label: 'Jamaica', value: 'JM', icon: '🇯🇲' },
  { label: 'Japan', value: 'JP', icon: '🇯🇵' },
  { label: 'Jordan', value: 'JO', icon: '🇯🇴' },
  // K
  { label: 'Kazakhstan', value: 'KZ', icon: '🇰🇿' },
  { label: 'Kenya', value: 'KE', icon: '🇰🇪' },
  { label: 'Kuwait', value: 'KW', icon: '🇰🇼' },
  { label: 'Kyrgyzstan', value: 'KG', icon: '🇰🇬' },
  // L
  { label: 'Laos', value: 'LA', icon: '🇱🇦' },
  { label: 'Latvia', value: 'LV', icon: '🇱🇻' },
  { label: 'Lebanon', value: 'LB', icon: '🇱🇧' },
  { label: 'Lesotho', value: 'LS', icon: '🇱🇸' },
  { label: 'Liberia', value: 'LR', icon: '🇱🇷' },
  { label: 'Libya', value: 'LY', icon: '🇱🇾' },
  { label: 'Liechtenstein', value: 'LI', icon: '🇱🇮' },
  { label: 'Lithuania', value: 'LT', icon: '🇱🇹' },
  { label: 'Luxembourg', value: 'LU', icon: '🇱🇺' },
  // M
  { label: 'Macao', value: 'MO', icon: '🇲🇴' },
  { label: 'Macedonia', value: 'MK', icon: '🇲🇰' },
  { label: 'Madagascar', value: 'MG', icon: '🇲🇬' },
  { label: 'Malawi', value: 'MW', icon: '🇲🇼' },
  { label: 'Malaysia', value: 'MY', icon: '🇲🇾' },
  { label: 'Maldives', value: 'MV', icon: '🇲🇻' },
  { label: 'Mali', value: 'ML', icon: '🇲🇱' },
  { label: 'Malta', value: 'MT', icon: '🇲🇹' },
  { label: 'Mauritania', value: 'MR', icon: '🇲🇷' },
  { label: 'Mauritius', value: 'MU', icon: '🇲🇺' },
  { label: 'Mexico', value: 'MX', icon: '🇲🇽' },
  { label: 'Moldova', value: 'MD', icon: '🇲🇩' },
  { label: 'Monaco', value: 'MC', icon: '🇲🇨' },
  { label: 'Mongolia', value: 'MN', icon: '🇲🇳' },
  { label: 'Montenegro', value: 'ME', icon: '🇲🇪' },
  { label: 'Morocco', value: 'MA', icon: '🇲🇦' },
  { label: 'Mozambique', value: 'MZ', icon: '🇲🇿' },
  { label: 'Myanmar', value: 'MM', icon: '🇲🇲' },
  // N
  { label: 'Namibia', value: 'NA', icon: '🇳🇦' },
  { label: 'Nepal', value: 'NP', icon: '🇳🇵' },
  { label: 'Netherlands', value: 'NL', icon: '🇳🇱' },
  { label: 'New Zealand', value: 'NZ', icon: '🇳🇿' },
  { label: 'Nicaragua', value: 'NI', icon: '🇳🇮' },
  { label: 'Niger', value: 'NE', icon: '🇳🇪' },
  { label: 'North Korea', value: 'KP', icon: '🇰🇵' },
  { label: 'Norway', value: 'NO', icon: '🇳🇴' },
  // O
  { label: 'Oman', value: 'OM', icon: '🇴🇲' },
  // P
  { label: 'Pakistan', value: 'PK', icon: '🇵🇰' },
  { label: 'Palestine', value: 'PS', icon: '🇵🇸' },
  { label: 'Panama', value: 'PA', icon: '🇵🇦' },
  { label: 'Papua New Guinea', value: 'PG', icon: '🇵🇬' },
  { label: 'Paraguay', value: 'PY', icon: '🇵🇾' },
  { label: 'Peru', value: 'PE', icon: '🇵🇪' },
  { label: 'Philippines', value: 'PH', icon: '🇵🇭' },
  { label: 'Poland', value: 'PL', icon: '🇵🇱' },
  { label: 'Portugal', value: 'PT', icon: '🇵🇹' },
  { label: 'Puerto Rico', value: 'PR', icon: '🇵🇷' },
  // Q
  { label: 'Qatar', value: 'QA', icon: '🇶🇦' },
  // R
  { label: 'Romania', value: 'RO', icon: '🇷🇴' },
  { label: 'Russia', value: 'RU', icon: '🇷🇺' },
  { label: 'Rwanda', value: 'RW', icon: '🇷🇼' },
  // S
  { label: 'Saudi Arabia', value: 'SA', icon: '🇸🇦' },
  { label: 'Senegal', value: 'SN', icon: '🇸🇳' },
  { label: 'Serbia', value: 'RS', icon: '🇷🇸' },
  { label: 'Seychelles', value: 'SC', icon: '🇸🇨' },
  { label: 'Sierra Leone', value: 'SL', icon: '🇸🇱' },
  { label: 'Singapore', value: 'SG', icon: '🇸🇬' },
  { label: 'Slovakia', value: 'SK', icon: '🇸🇰' },
  { label: 'Slovenia', value: 'SI', icon: '🇸🇮' },
  { label: 'Somalia', value: 'SO', icon: '🇸🇴' },
  { label: 'South Africa', value: 'ZA', icon: '🇿🇦' },
  { label: 'South Korea', value: 'KR', icon: '🇰🇷' },
  { label: 'Spain', value: 'ES', icon: '🇪🇸' },
  { label: 'Sri Lanka', value: 'LK', icon: '🇱🇰' },
  { label: 'Sudan', value: 'SD', icon: '🇸🇩' },
  { label: 'Sweden', value: 'SE', icon: '🇸🇪' },
  { label: 'Switzerland', value: 'CH', icon: '🇨🇭' },
  { label: 'Syria', value: 'SY', icon: '🇸🇾' },
  // T
  { label: 'Taiwan', value: 'TW', icon: '🇹🇼' },
  { label: 'Tajikistan', value: 'TJ', icon: '🇹🇯' },
  { label: 'Tanzania', value: 'TZ', icon: '🇹🇿' },
  { label: 'Thailand', value: 'TH', icon: '🇹🇭' },
  { label: 'Togo', value: 'TG', icon: '🇹🇬' },
  { label: 'Tunisia', value: 'TN', icon: '🇹🇳' },
  { label: 'Turkey', value: 'TR', icon: '🇹🇷' },
  { label: 'Turkmenistan', value: 'TM', icon: '🇹🇲' },
  // U
  { label: 'Uganda', value: 'UG', icon: '🇺🇬' },
  { label: 'Ukraine', value: 'UA', icon: '🇺🇦' },
  { label: 'United Arab Emirates', value: 'AE', icon: '🇦🇪' },
  { label: 'United Kingdom', value: 'GB', icon: '🇬🇧' },
  { label: 'United States', value: 'US', icon: '🇺🇸' },
  { label: 'Uruguay', value: 'UY', icon: '🇺🇾' },
  { label: 'Uzbekistan', value: 'UZ', icon: '🇺🇿' },
  // V
  { label: 'Venezuela', value: 'VE', icon: '🇻🇪' },
  { label: 'Vietnam', value: 'VN', icon: '🇻🇳' },
  // Y
  { label: 'Yemen', value: 'YE', icon: '🇾🇪' },
  // Z
  { label: 'Zambia', value: 'ZM', icon: '🇿🇲' },
  { label: 'Zimbabwe', value: 'ZW', icon: '🇿🇼' },
];
